### ISSUE TITLE
📄 Automatic keywords extraction

### ISSUE THREAD

**Issue by makma** [Kentico/kontent-custom-element-samples#63]
### Motivation

The author of the article/blog post wants to extract keywords/entities automatically.  

### Proposed solution
- Get content from the element (https://developer.kenticocloud.com/reference#getelementvalue-method).
- Utilize text analysis API (e.g. https://azure.microsoft.com/en-us/services/cognitive-services/text-analytics/)
- Make picker/selector for proposed terms/entities.
- Store selected values.

**Comment by Simply007** [comment]
Possible alternative:
* https://www.ibm.com/watson/services/natural-language-understanding/

**Comment by ChristopherJennings** [comment]
Also possible without relaying on a service: https://github.com/benmcevoy/Rake

**Comment by petrsvihlik** [comment]
https://github.com/Kentico/kontent-custom-element-keyword-extractor

**Comment by petrsvihlik** [comment]
@ChristopherJennings  will you please include a gif in the https://kentico.github.io/kontent-custom-element-samples/gallery/ ?
