### ISSUE TITLE
☯️ Font awesome selector

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/kontent-custom-element-samples#67]
### Motivation

Allow to preview and select [font awesome](https://fontawesome.com/) icons.

**Comment by petrsvihlik** [comment]
https://github.com/Simply007/kontent-custom-element-font-awesome-selector
https://github.com/yuriys-kentico/FontAwesomeIcons/tree/multiple-icons
https://stackblitz.com/edit/fontawesomeselector

**Comment by Simply007** [comment]
Final repositories:
* https://github.com/Simply007/kontent-custom-element-font-awesome-selector-svg
* https://github.com/Simply007/kontent-custom-element-font-awesome-selector-codename

**Comment by petrsvihlik** [comment]
This is great @Simply007 !
Do we want to close this one? Or is there still some outstanding work? 
Perhaps adding the selectors to https://kentico.github.io/kontent-custom-element-samples/gallery/?

**Comment by petrsvihlik** [comment]
Oh, I see it now: https://github.com/Kentico/kontent-custom-element-samples/pull/91
