### ISSUE TITLE
🔗 Broken Link Checker

### ISSUE THREAD

**Issue by ChristopherJennings** [Kentico/kontent-custom-element-samples#77]
### Motivation

When linking to URLs, sometimes those URLs change or become unavailable over time. This would help editors find and resolve them. 

### Proposed solution

* Get content from the text/rich text elements ([Docs](https://developer.kenticocloud.com/reference#getelementvalue-method)).
* Extract all URLs using a regex pattern or similar
* Use a tool like [CORS anywhere](https://github.com/Rob--W/cors-anywhere/) to get around any potential CORS issues
* Report the list of links that do not resolve to a 200 status code so the editor can find and fix them.
* Save a value if there are no issues and null if there are so that if the element is marked required it will properly show up in the Kontent UI

**Comment by hzik** [comment]
https://github.com/hzik/LinkChecker
